# Generated by Django 3.2.9 on 2021-11-07 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('reading', models.FloatField()),
                ('device_id', models.UUIDField()),
                ('customer_id', models.UUIDField()),
            ],
        ),
    ]
