# Generated by Django 3.2.9 on 2021-11-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
