


# refs:
# https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/
# https://drive.google.com/drive/folders/1LaCepVp8mzslwq7qUC864Y_7fT9d0a2E

# TODOs:
# add latest version
# root project as the context for each services, because of .dockerignore file
# add services from services folder

