

# TODOs : complete below structure for other services, network and volumes for services folder based on their Dockerfiles

version: '3.3'
services:
  web:
    build:
      context: ./
      dockerfile: ./services/server/api/core/Dockerfile
    volumes:
      - core-servers:/usr/src/app
    expose:
      - 8587
    networks:
      - app-net      
networks:
  app-net:
    driver: bridge
volumes:
  core-servers:
