


# refs:
# https://testdriven.io/blog/dockerizing-flask-with-postgres-gunicorn-and-nginx/
# https://drive.google.com/drive/folders/1LaCepVp8mzslwq7qUC864Y_7fT9d0a2E

# TODOs:
# add latest version
# build microservices like rust for telegram bot, cassandra, traefik or nginx, k8s and fastapi from their Dockerfile inside services folder
