



// TODO - build a low cost in time and cheap consensus algorithm like a proof of stake based on coiniXerr peers features and an AI core like SSL models like Transformers 
// NOTE - peer can have a successful coin transfer process once their transaction is added to the blockchain (add mined transaction to the block structure then add the block to the Chain tree)
// NOTE - coiniXerr netowkr will pay all its peers at the end of each week; their credit score coins generated by AI + reward of mined transactions
// NOTE - every peer is also a miner cause we have an AI core which will generate credit score coins based on peer position clustering process
// NOTE - mining rate of the uniXerr coins will be evaluated every month based on total average of all peers' efforts
// NOTE - mining rate < 0.5 means uniXerr net worth and stocks is about to falling and mining rate > 0.5 means the uniXerr stocks is about to rising and generate more coins
// NOTE - more transactions from a user the network gets per week; more bonus coins he/she gets paied besides his/her own reward
// ...