


# TODOs:
# FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8
# create uniXerr group and user with password
# move the whole project into the uniXerr home directory
# install all necessary dependencies like installing from requirements.txt or form uniXerr.yml file in conda env
# change the owner of the folder containing the source code
# secure api.py inside server folder using https://fastapi.tiangolo.com/tutorial/security/
# run the fastapi server in development mode using "typer app.py run develop" command
