


# refs:
# https://github.com/patrick-fitzgerald/actix-web-docker-example
# https://github.com/telegram-rs/telegram-bot
# https://github.com/teloxide/teloxide


# TODOs:
# FROM ekidd/rust-musl-builder:stable as builder
# serve pre-trained core AI models with rust using tch, tokio, actix, rocket, hyper, docker and k8s based on streaming async paradigm
# implement uPC telegram bot in rust using actix, tokio and zmq

