




# TODOs
# pull a pytorch cuda image to run core folder AI models
# create uniXerr group and user with password
# move the whole project, especially core folder, into the uniXerr home directory
# install all necessary dependencies like installing from requirements.txt or form uniXerr.yml file in conda env
# change the owner of the folder containing the source code
