



// TODO - build a low cost in time and cheap consensus algorithm like a proof of stake based on coiniXerr peers features 
// TODO - to issue a smart contract the consensus algorithm or mining process must be done first
// TODO - after mining process has completed a smart contract will be issued to sign each transaction
// TODO - finally each smart contract will be added to the coiniXerr blockchain (add mined transaction to the Block structure then add the block to the Chain tree)
// NOTE - peer can have a successful coin transfer process once a smart contract is added to the blockchain
// NOTE - coiniXerr netowkr will pay all its peers at the end of each month; their credit score coins generated by AI + reward of mined transactions
// NOTE - every peer is also a miner cause we have an AI core which will generate credit score coins based on peer position clustering process
// NOTE - more transactions from a user the network gets per month; more reward he/she gets paied  
// NOTE - public key is used to generate wallet address and private key is used to sign blockchain based transactions
// ...