'''
------------------------------------------------------------
 DOUBLE AUTHENTICATING PREVENTER USING RNNs AND BLOCKCHAIN
------------------------------------------------------------
                |p2p network for blockchain|



        |=> check a user data by using ai to see that he/she is already logged in or not : verifying authenticity! <=|
        |=> after validating each user they will mine and add to the blockchain ledger by this network for later usage of epcbm network <=|
        |=> after uniXerr users are added to the blockchain ledger the uniXerr protocol will give 10 coins to everyone by default <=| 
        |=> new predictions (generated by epcbm NETWORK) for each user will add to the uniXerr blockchain ledger for later predictions <=|
        |=> to mine a block (add users predictions to a block) we use an ai algorithm like clustering to verify the predictions and user authenticity validation <=|
        |=> after the blocks are mined and added to the chain with no problem, predicted coins by epcbm NETWORK will give to each user <=|
        |=> finally we'll sotore the whole blockchain in a mongo database <=|
'''

import plotly.graph_objects as go