[package]
name = "solaient"
version = "0.1.0"
edition = "2021"




[dependencies]
solana-client = "1.8.8"
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"