[package]
name = "freewifi"
version = "0.1.0"
authors = ["user29 <erfan@araglobal.ir>"]



[dependencies]
actix-web = "3"
tokio = { version = "1", features = ["full"] }
hyper = "0.14"
rocket = "0.4.7"


[[bin]]
name = "freewifi"
path = "src/main.rs"

